polis/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers

from polls.views import ChoiceList
from . import views

router = routers.DefaultRouter()
router.register(r'choice', views.ChoiceViewSet)
router.register(r'question', views.QuestionViewSet)

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('questions/add/', views.show_create_question_page, name='addQuestion'),
    path('questions/created/', views.create_question, name='questionCreated'),
    path('questions/<int:question_id>/choices/added/', views.create_choice, name='choiceAdded'),

    ## REST URLS ##
    url(r'^', include(router.urls)),
    url('^choice/(?P<username>.+)/$', ChoiceList.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

user/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'api', views.UserViewSet)

app_name = 'user'
urlpatterns = [
    path('new/user', views.create_user_page, name='create'),
    path('user/added', views.create_user, name='addUser'),
    path('login/', views.login_page, name='login'),
    path('welcome/', views.user_login, name='welcome'),

    ## REST URLS ##
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class ChoiceSelected(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    selection_made = models.BooleanField(False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from rest_framework import viewsets, status, generics
from rest_framework.decorators import list_route
from rest_framework.response import Response

from polls.serializers import ChoiceSerializer, QuestionSerializer
from django.contrib.auth.models import User
from .models import Choice, Question, ChoiceSelected
from django.views import generic
from .exceptions import Error, AlreadyVoted
import datetime


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class ChoiceViewSet(viewsets.ModelViewSet):
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer
    lookup_field = 'question'

    def get(self):
        choice = Choice.values_list('question', flat=True)
        return choice


class ChoiceList(generics.ListAPIView):
    serializer_class = ChoiceSerializer

    def get_queryset(self):
        """
        This view should return a list of all the purchases for
        the user as determined by the username portion of the URL.
        """
        question = self.kwargs['question']
        return Choice.objects.filter(question=question)


class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer
    lookup_field = 'id'

    def post(self):
        serializer = QuestionSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self):
        serializer = QuestionSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self):
        serializer = QuestionSerializer(data=request.data)
        if serializer.is_valid():
            serializer.delete()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def show_create_question_page(request):
    return render(request, 'polls/create.html')


def create_question(request):
    question = request.POST['question']
    q = Question(question_text=question, pub_date=datetime.datetime.now())
    q.save()
    return show_create_choices_page(request, q.id)


def show_create_choices_page(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/addchoices.html', {'question': question})


def create_choice(request, question_id):
    choice = request.POST['choice']
    question = get_object_or_404(Question, pk=question_id)
    c = Choice(question=question, choice_text=choice, votes=0)
    c.save()
    return render(request, 'polls/addchoices.html', {'question': question})


def user_has_voted(request, question_id):
    question = Question.objects.get(pk=question_id)
    choice_selected = ChoiceSelected.objects.filter(question=question, user=request.user).exists()
    if choice_selected is False:
        return False
    else:
        raise AlreadyVoted


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        user_has_voted(request, question_id)
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist, AlreadyVoted):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice, or have already voted.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        selected_by = ChoiceSelected(choice=selected_choice, question=question, selection_made=True, user=request.user)
        selected_by.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'polls/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})
#
#

polls/templates/polls/addchoices.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'polls:choiceAdded' question.id %}" method="post">
{% csrf_token %}
    <input type="text" name="choice" id="choice" />
    <label>Poll Option</label><br />
    <input type="submit" value="Create" />
</form>
<a href="{% url 'polls:index' %}">Done</a>
</body>
</html>

polls/templates/polls/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% if user.is_authenticated %}
<form action="{% url 'polls:questionCreated' %}" method="post">
{% csrf_token %}
    <input type="text" name="question" id="question" />
    <label>Poll Title</label><br />
    <input type="submit" value="Create" />
</form>
{% else %}
<p>You must be logged in to create a poll</p>
{% endif %}
</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
<a href="{% url 'polls:results' question.id %}">View Results</a>
</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    <li><a href="{% url 'user:login' %}">Login</a></li>
    <li><a href="{% url 'user:create' %}">Create Account</a></li>
</ul>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:welcome' %}" method="post">
{% csrf_token %}
    <input type="text" name="username" id="username" />
    <label>Username</label><br />
    <input type="password" name="password" id="password" />
    <label>Password</label><br />
    <input type="submit" value="Login" />
</form>
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>