polis/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers

from polls.views import ChoiceList
from . import views

router = routers.DefaultRouter()
router.register(r'choice', views.ChoiceViewSet)
router.register(r'question', views.QuestionViewSet)

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('questions/add/', views.show_create_question_page, name='addQuestion'),
    path('questions/created/', views.create_question, name='questionCreated'),
    path('questions/<int:question_id>/choices/added/', views.create_choice, name='choiceAdded'),

    ## REST URLS ##
    url(r'^', include(router.urls)),
    url('^choice/(?P<username>.+)/$', ChoiceList.as_view()),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

user/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'api', views.UserViewSet)

app_name = 'user'
urlpatterns = [
    path('new/user', views.create_user_page, name='create'),
    path('user/added', views.create_user, name='addUser'),
    path('login/', views.login_page, name='login'),
    path('welcome/', views.user_login, name='welcome'),

    ## REST URLS ##
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

user/models.py
from django.db import models

user/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import render
from rest_framework import viewsets, status
from rest_framework.response import Response

from user.serializers import UserSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'id'

    def post(self, request):
        serializer = UserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request):
        serializer = UserSerializer(data=request.method)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request):
        serializer = UserSerializer(data=request.method)
        if serializer.is_valid():
            serializer.delete()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def create_user_page(request):
    return render(request, 'user/newuser.html')


def create_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    password1 = request.POST['retype-password']
    if password == password1:
        u = User.objects.create_user(username=username, email=email, password=password, is_active=1)
        u.save()
        return render(request, 'polls/index.html')
    else:
        return render(request, 'user/newuser.html')


def login_page(request):
    return render(request, 'user/login.html')


def user_login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return render(request, 'user/welcome.html')
    else:
        EOFError('Invalid username or password')

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'user:welcome' %}" method="post">
{% csrf_token %}
    <input type="text" name="username" id="username" />
    <label>Username</label><br />
    <input type="password" name="password" id="password" />
    <label>Password</label><br />
    <input type="submit" value="Login" />
</form>
</body>
</html>

user/templates/user/newuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'user:addUser' %}" method="post">
{% csrf_token %}
    <input type="text" name="username" id="username" />
    <label>Username</label><br />
    <input type="text" name="email" id="email" />
    <label>Email Address</label><br />
    <input type="password" name="password" id="password" />
    <label>Password</label><br />
    <input type="password" name="retype-password" id="retype-password" />
    <label>Re-type Password</label><br />
    <input type="submit" value="Login" />
<input type="submit" value="Vote" />
</form>
</body>
</html>

user/templates/user/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Welcome {{ request.user.username }}
<a href="{% url 'polls:addQuestion' %}">Create Poll</a>
</body>
</html>